using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GTAVBattleRoyaleMain {
    class GameData {

        public static string player_name = "mrroibot";
        public static string[] bot_names = {
            "Gooze",
            "Cyborne",
            "Falconjure",
            "Decorsair",
            "JellyFairy",
            "ShinyBuffalo",
            "FamousPig",
            "ImpulsePanda",
            "GlamorousLemur",
            "HorriblePirate",
            "Gamerman",
            "Zebrass",
            "Grapeshifter",
            "Madept",
            "ScentedDoughnut",
            "JellySerpent",
            "CruelSalamander",
            "IcyCoconut",
            "TimeMaverick",
            "CannonVampire",
            "Domignome",
            "Bingoliath",
            "Valord",
            "Herose",
            "TroubledWizard",
            "RapidRaspberry",
            "EuphoricSpook",
            "HammerGnoll",
            "PeaceFurry",
            "VioletGoblin",
            "MatriarchMage",
            "Porcupity",
            "Gamercenary",
            "Blazebra",
            "ChargeWillow",
            "JungleTrooper",
            "LunchBat",
            "EagerKing",
            "StylishPorcupine",
            "EmbarrasedHawk",
            "Raptortoise",
            "Bonsiren",
            "MammothMoth",
            "Aquasp",
            "HealthyDiva",
            "SubtleStork",
            "GrandWhale",
            "SwiftNugget",
            "GlamorousQueen",
            "ArtisticRascal",
            "Flexecutioner",
            "Koalassy",
            "Sundaemon",
            "Gorillamp",
            "CreepyAlmond",
            "SubtleArrow",
            "PureLeaf",
            "CoachOctopus",
            "WindWhale",
            "HonestTea",
            "Herogue",
            "Cloverseer",
            "Lavampire",
            "Vikingpin",
            "AshKing",
            "RecordTiger",
            "ProudLarva",
            "DoomBlizzard",
            "OrangeElf",
            "PaperPapaya",
            "Tabooccaneer",
            "Donkeychain",
            "Grapeshifter",
            "Camperor",
            "RoomOctopus",
            "OpinionGrape",
            "BadBerry",
            "ObviousGoat",
            "WriterColonel",
            "RiddleChamp",
            "Cocowboy",
            "Essaint",
            "Cowhale",
            "Valord",
            "GrassPie",
            "VolcanoCoyote",
            "SlowBrownie",
            "ClubHero",
            "SpottedColt",
            "FruitOcelot",
            "Hedgehog",
            "Jalapegnome",
            "Techgnome",
            "Scraptor",
            "PaperKiwi",
            "VirtualLion",
            "BrotherOctopus",
            "PhantomHeroine",
            "BrutishChicken",
            "SchoolGull",
            "Bambinosaur",
            "Consoldier",
            "BuffaLou",
            "Plazy",
            "PartyHeroine",
            "ElectricGuardian",
            "MarbleEnigma",
            "PeacefulNova",
            "IdenticalEnigma",
            "HiddenSquire"
        };
        public static Dictionary<string, string> weaponComponentItems = new Dictionary<string, string>() {
                { "SWAP_DEFAULT", "SWAP_DEFAULT" },
                { "SWAP_MELEE_2H", "SWAP_MELEE_2H" },
                { "RELOAD_DEFAULT", "RELOAD_DEFAULT" },
                { "RELOAD_LARGE", "RELOAD_LARGE" },
                { "RELOAD_DEFAULT_WITH_EMPTIES", "RELOAD_DEFAULT_WITH_EMPTIES" },
                { "RELOAD_LARGE_WITH_EMPTIES", "RELOAD_LARGE_WITH_EMPTIES" },
                { "RELOAD_ONLY_AIM", "RELOAD_ONLY_AIM" },
                { "RELOAD_LARGE_ONLY_AIM", "RELOAD_LARGE_ONLY_AIM" },
                { "RELOAD_DEFAULT_BOTH_SIDES", "RELOAD_DEFAULT_BOTH_SIDES" },
                { "COMPONENT_AT_RAILCOVER_01", "COMPONENT_AT_RAILCOVER_01" },
                { "COMPONENT_AT_AR_AFGRIP", "Grip" },
                { "COMPONENT_AT_PI_FLSH", "Flashlight" },
                { "COMPONENT_AT_AR_FLSH", "Flashlight" },
                { "POLICE_TORCH_FLASHLIGHT", "POLICE_TORCH_FLASHLIGHT" },
                { "COMPONENT_AT_SCOPE_MACRO", "Scope" },
                { "COMPONENT_AT_SCOPE_MACRO_02", "Scope" },
                { "COMPONENT_AT_SCOPE_SMALL", "Scope" },
                { "COMPONENT_AT_SCOPE_SMALL_02", "Scope" },
                { "COMPONENT_AT_SCOPE_MEDIUM", "Scope" },
                { "COMPONENT_AT_SCOPE_LARGE", "Scope" },
                { "COMPONENT_AT_SCOPE_MAX", "Advanced Scope" },
                { "COMPONENT_AT_PI_SUPP", "Supressor" },
                { "COMPONENT_AT_PI_SUPP_02", "Supressor" },
                { "COMPONENT_AT_AR_SUPP", "Supressor" },
                { "COMPONENT_AT_AR_SUPP_02", "Supressor" },
                { "COMPONENT_AT_SR_SUPP", "Supressor" },
                { "COMPONENT_AT_SR_SUPP_02", "Supressor" },
                { "COMPONENT_PISTOL_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_PISTOL_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_COMBATPISTOL_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_COMBATPISTOL_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_APPISTOL_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_APPISTOL_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_MICROSMG_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_MICROSMG_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_SMG_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_SMG_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_ASSAULTRIFLE_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_ASSAULTRIFLE_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_CARBINERIFLE_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_CARBINERIFLE_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_ADVANCEDRIFLE_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_ADVANCEDRIFLE_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_MG_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_MG_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_COMBATMG_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_COMBATMG_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_ASSAULTSHOTGUN_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_ASSAULTSHOTGUN_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_PISTOL50_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_PISTOL50_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_ASSAULTSMG_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_ASSAULTSMG_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_HEAVYPISTOL_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_HEAVYPISTOL_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_SPECIALCARBINE_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_SPECIALCARBINE_CLIP_02", "Extended Clip-Siz" },
                { "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM", "Scope" },
                { "COMPONENT_MARKSMANRIFLE_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_MARKSMANRIFLE_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_HEAVYSHOTGUN_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_HEAVYSHOTGUN_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_COMBATPDW_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_COMBATPDW_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_SNSPISTOL_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_SNSPISTOL_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_BULLPUPRIFLE_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_BULLPUPRIFLE_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_VINTAGEPISTOL_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_VINTAGEPISTOL_CLIP_02", "Extended Clip-Size" },
                { "COMPONENT_GUSENBERG_CLIP_01", "Normal Clip-Size" },
                { "COMPONENT_GUSENBERG_CLIP_02", "Extended Clip-Size" },
            };
    }
}
